use crate::clock::Clock;
use bw_crypto::DeviceId;
use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::{Arc, RwLock};

/// Maximum forwarding payload size in bytes. Packets exceeding this are dropped.
/// Set to QUIC minimum MTU minus the 32-byte relay routing header overhead.
pub const MAX_FORWARDING_PAYLOAD: usize = 1168;

/// Maximum raw packet size permitted on the relay data plane (header + payload).
pub const MAX_PACKET_SIZE: usize = 1200;

/// Idle timeout after which an active forwarding context is expired (30 seconds).
const IDLE_TIMEOUT_MS: u64 = 30_000;

/// Lifecycle state of a relay forwarding context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ForwardingState {
    /// Both endpoints are authorized but no EstablishRequest has been received yet.
    Authorized,
    /// At least one endpoint has bound its data-plane address; waiting for the other.
    RelayRequested,
    /// Both endpoints are bound; actively forwarding packets.
    RelayActive,
    /// The context has exceeded its idle timeout; no further forwarding is allowed.
    RelayExpired,
    /// The context was explicitly closed by a disconnect or revocation.
    RelayClosed,
}

/// The authenticated network binding for one endpoint in a forwarding pair.
#[derive(Debug, Clone)]
pub struct EndpointBinding {
    /// The authenticated device identity of this endpoint.
    pub device_id: DeviceId,
    /// The most recently authenticated data-plane SocketAddr for this endpoint.
    pub addr: Option<SocketAddr>,
}

/// A live forwarding context binding a relay token to exactly two authenticated endpoints.
///
/// The relay token is the only identifier used on the data plane.
/// Endpoint addresses are validated against their authenticated bindings on every packet.
pub struct ForwardingContext {
    /// The Phase 2 intent identifier that produced this forwarding context.
    pub intent_id: [u8; 16],
    /// The 32-byte relay routing token used to identify this session on the data plane.
    pub token: [u8; 32],
    /// The initiating endpoint's authenticated binding.
    pub initiator: EndpointBinding,
    /// The target endpoint's authenticated binding.
    pub target: EndpointBinding,
    /// The current lifecycle state of this forwarding context.
    pub state: ForwardingState,
    /// Timestamp (ms) of the last forwarded packet, used for idle-timeout tracking.
    pub last_active_ms: u64,
}

/// The forwarding table: O(1) lookup from token to context, with idle-timeout enforcement.
///
/// # Security model
/// - A context is only created after both parties' identities are signed and verified
///   during the Phase 2 rendezvous handshake.
/// - Forwarding is only permitted when the source address exactly matches the registered
///   binding for the initiator or target.
/// - Spoofed or unassociated source addresses are silently dropped.
/// - NAT rebinding is only accepted via a new signed `RelayEstablishRequest`.
pub struct ForwardingTable {
    /// Primary store: intent_id -> context.
    contexts: RwLock<HashMap<[u8; 16], ForwardingContext>>,
    /// Fast routing index: relay_token -> intent_id.
    token_index: RwLock<HashMap<[u8; 32], [u8; 16]>>,
    clock: Arc<dyn Clock>,
}

impl ForwardingTable {
    /// Creates a new, empty forwarding table backed by the given clock.
    pub fn new(clock: Arc<dyn Clock>) -> Self {
        Self {
            contexts: RwLock::new(HashMap::new()),
            token_index: RwLock::new(HashMap::new()),
            clock,
        }
    }

    /// Registers a forwarding pair after successful Phase 2 mutual authorization.
    ///
    /// The token is generated by the relay during `AcceptConnect` and is never known
    /// to the relay before that point; it is distributed via `CandidateExchange`.
    pub fn authorize_pair(
        &self,
        intent_id: [u8; 16],
        token: [u8; 32],
        initiator_id: DeviceId,
        target_id: DeviceId,
    ) {
        let now = self.clock.now_ms();
        let ctx = ForwardingContext {
            intent_id,
            token,
            initiator: EndpointBinding {
                device_id: initiator_id,
                addr: None,
            },
            target: EndpointBinding {
                device_id: target_id,
                addr: None,
            },
            state: ForwardingState::Authorized,
            last_active_ms: now,
        };

        self.contexts.write().unwrap_or_else(|e| e.into_inner()).insert(intent_id, ctx);
        self.token_index.write().unwrap_or_else(|e| e.into_inner()).insert(token, intent_id);
    }

    /// Authenticates and records the data-plane SocketAddr for one endpoint of the pair.
    ///
    /// This is the only mechanism by which the relay accepts a new or changed source
    /// address. It requires a fresh signed `RelayEstablishRequest`; token possession
    /// alone is insufficient.
    pub fn update_binding(
        &self,
        intent_id: [u8; 16],
        device_id: DeviceId,
        addr: SocketAddr,
    ) -> Result<(), &'static str> {
        let now = self.clock.now_ms();
        let mut contexts = self.contexts.write().unwrap_or_else(|e| e.into_inner());

        let ctx = contexts.get_mut(&intent_id).ok_or("Forwarding session not found")?;

        // Reject updates to terminated or expired contexts.
        match ctx.state {
            ForwardingState::RelayExpired | ForwardingState::RelayClosed => {
                return Err("Cannot rebind a closed or expired forwarding session");
            }
            _ => {}
        }

        // Idle-timeout check during binding.
        if now.saturating_sub(ctx.last_active_ms) > IDLE_TIMEOUT_MS {
            ctx.state = ForwardingState::RelayExpired;
            return Err("Forwarding session has expired due to inactivity");
        }

        // Only the authorized pair members may update bindings.
        if ctx.initiator.device_id == device_id {
            ctx.initiator.addr = Some(addr);
        } else if ctx.target.device_id == device_id {
            ctx.target.addr = Some(addr);
        } else {
            return Err("Device is not part of this forwarding session");
        }

        ctx.last_active_ms = now;

        // Advance state machine.
        ctx.state = if ctx.initiator.addr.is_some() && ctx.target.addr.is_some() {
            ForwardingState::RelayActive
        } else {
            ForwardingState::RelayRequested
        };

        Ok(())
    }

    /// Looks up the destination address for a forwarded packet.
    ///
    /// Returns `None` and silently drops the packet if:
    /// - The token is unknown.
    /// - The context is not in `RelayActive` state.
    /// - The source address does not match the registered binding (anti-spoofing).
    /// - The idle timeout has been exceeded.
    ///
    /// No error is returned to avoid leaking information to potential attackers.
    pub fn get_destination(
        &self,
        token: &[u8; 32],
        source_addr: SocketAddr,
    ) -> Option<SocketAddr> {
        let now = self.clock.now_ms();

        let intent_id = {
            let idx = self.token_index.read().unwrap_or_else(|e| e.into_inner());
            *idx.get(token)?
        };

        let mut contexts = self.contexts.write().unwrap_or_else(|e| e.into_inner());
        let ctx = contexts.get_mut(&intent_id)?;

        if ctx.state != ForwardingState::RelayActive {
            return None;
        }

        // Idle timeout enforcement.
        if now.saturating_sub(ctx.last_active_ms) > IDLE_TIMEOUT_MS {
            ctx.state = ForwardingState::RelayExpired;
            return None;
        }

        let init_addr = ctx.initiator.addr?;
        let targ_addr = ctx.target.addr?;

        // Source must exactly match one of the two authorized bindings.
        // An unregistered or spoofed source address results in a silent drop.
        if source_addr == init_addr {
            ctx.last_active_ms = now;
            Some(targ_addr)
        } else if source_addr == targ_addr {
            ctx.last_active_ms = now;
            Some(init_addr)
        } else {
            None
        }
    }

    /// Explicitly closes a forwarding context (endpoint disconnect or revocation).
    pub fn close(&self, intent_id: [u8; 16]) {
        if let Ok(mut contexts) = self.contexts.write()
            && let Some(ctx) = contexts.get_mut(&intent_id)
        {
            ctx.state = ForwardingState::RelayClosed;
        }
    }

    /// Sweeps expired and closed contexts and removes their token index entries.
    ///
    /// Should be called periodically by a background task to bound memory usage.
    pub fn sweep(&self) -> usize {
        let now = self.clock.now_ms();
        let mut contexts = self.contexts.write().unwrap_or_else(|e| e.into_inner());
        let mut token_index = self.token_index.write().unwrap_or_else(|e| e.into_inner());

        let mut to_remove: Vec<[u8; 16]> = Vec::new();

        for (id, ctx) in contexts.iter_mut() {
            let timed_out = ctx.state == ForwardingState::RelayActive
                && now.saturating_sub(ctx.last_active_ms) > IDLE_TIMEOUT_MS;

            if timed_out {
                ctx.state = ForwardingState::RelayExpired;
            }

            let is_terminal = matches!(
                ctx.state,
                ForwardingState::RelayExpired | ForwardingState::RelayClosed
            );
            if is_terminal {
                to_remove.push(*id);
            }
        }

        let count = to_remove.len();
        for id in to_remove {
            if let Some(ctx) = contexts.remove(&id) {
                token_index.remove(&ctx.token);
            }
        }
        count
    }

    /// Returns the current state of a forwarding context for testing/audit.
    pub fn state_of(&self, intent_id: &[u8; 16]) -> Option<ForwardingState> {
        self.contexts
            .read()
            .unwrap_or_else(|e| e.into_inner())
            .get(intent_id)
            .map(|c| c.state)
    }
}
