[package]
name = "bw-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bw-core = { path = "../bw-core" }
bw-crypto = { path = "../bw-crypto", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
thiserror = "1"
zeroize = { workspace = true }
bytemuck = { workspace = true }
ciborium = "0.2"

[[bench]]
name = "placeholder"
harness = false

