[package]
name = "bw-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
bw-core = { path = "../bw-core" }
bw-crypto = { path = "../bw-crypto" }
tokio = { workspace = true }
thiserror = "1.0"
serde = { workspace = true }
sha2 = "0.10"

[lints]
workspace = true

[dev-dependencies]
bw-crypto = { path = "../bw-crypto" }
